version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - share_f:/mnt/f
    ports:
      - '8080:80'
#  client:
#    build:
#      context: .
#      dockerfile: docker/client/Dockerfile
#    image: strangesast/qr_client
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: strangesast/qr_server
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  mongo:
    image: mongo
    ports:
      - 27017:27017
volumes:
  share_f:
    external: true
