version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    image: strangesast/qr_client
    ports:
      - 80:80
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: strangesast/qr_server
  db:
    image: mongo
    ports:
      - 27017:27017
