version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    image: strangesast/qr_client
    volumes:
      - share_f:/mnt/f
      - qr_imgs:/mnt/data
    ports:
      - '8080:80'
    restart: always
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: strangesast/qr_server
    volumes:
      - qr_imgs:/app/data
    environment:
      - ORIGIN=http://10.0.0.62:8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - qr_mongo:/data/db
    ports:
      - 27018:27017
volumes:
  share_f:
    external: true
  qr_mongo:
    external: true
  qr_imgs:
